import { AddEthereumChainParameter } from '@rabby-wallet/rabby-api/dist/types';
import { CHAINS, CHAINS_ENUM, NETWORK_TYPES, NETWORK_COLORS, NETWORK_URL, CHAIN_EXPLORERS, CHAIN_EXPLORERS_API, CHAIN_NATIVE_TOKEN, GAS_SYMBOL, CHAIN_INFO, INITIAL_CHAIN, SUPPORTED_CHAINS, CHAIN_ID_TO_CHAIN } from './networks.pulsechain';

export {
  CHAINS,
  CHAINS_ENUM,
  NETWORK_TYPES,
  NETWORK_COLORS,
  NETWORK_URL,
  CHAIN_EXPLORERS,
  CHAIN_EXPLORERS_API,
  CHAIN_NATIVE_TOKEN,
  GAS_SYMBOL,
  CHAIN_INFO,
  INITIAL_CHAIN,
  SUPPORTED_CHAINS,
  CHAIN_ID_TO_CHAIN
};
